#!/usr/bin/env python3
"""Builds Sumbee's icon set from sumbee-foreground.svg. Run from the repo root:

    python3 design/icon/build_icons.py

Writes:
  app/src/main/res/drawable/ic_launcher_foreground.xml   adaptive foreground + splash icon (vector)
  app/src/main/res/drawable/ic_launcher_monochrome.xml   themed-icon silhouette (Android 13+)
  app/src/main/res/mipmap-*/ic_launcher(_round).png      legacy icons for API 24–25
  design/icon/sumbee-full.svg                            foreground on its navy ground
  design/icon/play-store-512.png                         the Play listing icon (full bleed; Play rounds it)
  design/icon/play-feature-1024x500.png                  the Play feature graphic (text in the app's fonts)

Needs rsvg-convert (brew install librsvg). The vector XML below mirrors the SVG by hand, shape for
shape: change both together.
"""
import os
import re
import subprocess
import tempfile

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
HERE = os.path.dirname(os.path.abspath(__file__))
RES = os.path.join(ROOT, "app", "src", "main", "res")
NAVY, SUN, WHITE = "#1B2A4A", "#FFC93C", "#FFFFFF"


def circle(cx, cy, r):
    """A circle as path data (two arcs): VectorDrawable has no <circle>."""
    return f"M{cx - r},{cy} a{r},{r} 0 1,0 {2 * r},0 a{r},{r} 0 1,0 {-2 * r},0 z"


def ellipse(cx, cy, rx, ry):
    return f"M{cx - rx},{cy} a{rx},{ry} 0 1,0 {2 * rx},0 a{rx},{ry} 0 1,0 {-2 * rx},0 z"


# The plus on the body as a polygon, for the monochrome cut-out (a stroke can't cut a hole).
PLUS_HOLE = "M51,54 L57,54 L57,61 L64,61 L64,67 L57,67 L57,74 L51,74 L51,67 L44,67 L44,61 L51,61 Z"

FOREGROUND = f"""<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by design/icon/build_icons.py from sumbee-foreground.svg: a bee with a plus on its back. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <group android:rotation="-28" android:pivotX="38" android:pivotY="50">
        <path android:fillColor="{WHITE}" android:pathData="{ellipse(38, 50, 11.5, 7)}" />
    </group>
    <group android:rotation="28" android:pivotX="70" android:pivotY="50">
        <path android:fillColor="{WHITE}" android:pathData="{ellipse(70, 50, 11.5, 7)}" />
    </group>
    <path android:strokeColor="{SUN}" android:strokeWidth="2.4" android:strokeLineCap="round"
        android:pathData="M50,32 Q47.5,26 44,24.5 M58,32 Q60.5,26 64,24.5" />
    <path android:fillColor="{SUN}"
        android:pathData="{circle(44, 24.5, 2.6)} {circle(64, 24.5, 2.6)} M50.5,79 L54,86 L57.5,79 Z {circle(54, 64, 17)}" />
    <path android:fillColor="{SUN}" android:strokeColor="{NAVY}" android:strokeWidth="2.6"
        android:pathData="{circle(54, 40, 10.5)}" />
    <path android:strokeColor="{NAVY}" android:strokeWidth="6" android:strokeLineCap="round"
        android:pathData="M54,57 V71 M46,64 H62" />
    <path android:fillColor="{NAVY}" android:pathData="{circle(50.4, 39, 1.9)} {circle(57.6, 39, 1.9)}" />
    <path android:strokeColor="{NAVY}" android:strokeWidth="1.7" android:strokeLineCap="round"
        android:pathData="M50.6,43.2 Q54,46.2 57.4,43.2" />
</vector>
"""

MONOCHROME = f"""<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by design/icon/build_icons.py: the bee as one silhouette for themed icons (Android 13+);
     the system tints it. Eyes and the plus are holes (evenOdd). -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <group android:rotation="-28" android:pivotX="38" android:pivotY="50">
        <path android:fillColor="#FFFFFFFF" android:pathData="{ellipse(38, 50, 11.5, 7)}" />
    </group>
    <group android:rotation="28" android:pivotX="70" android:pivotY="50">
        <path android:fillColor="#FFFFFFFF" android:pathData="{ellipse(70, 50, 11.5, 7)}" />
    </group>
    <path android:strokeColor="#FFFFFFFF" android:strokeWidth="2.4" android:strokeLineCap="round"
        android:pathData="M50,32 Q47.5,26 44,24.5 M58,32 Q60.5,26 64,24.5" />
    <path android:fillColor="#FFFFFFFF"
        android:pathData="{circle(44, 24.5, 2.6)} {circle(64, 24.5, 2.6)} M50.5,79 L54,86 L57.5,79 Z" />
    <path android:fillColor="#FFFFFFFF" android:fillType="evenOdd"
        android:pathData="{circle(54, 64, 17)} {PLUS_HOLE}" />
    <path android:fillColor="#FFFFFFFF" android:fillType="evenOdd"
        android:pathData="{circle(54, 40, 10.5)} {circle(50.4, 39, 1.9)} {circle(57.6, 39, 1.9)}" />
</vector>
"""


def full_svg(size, scale=1.0, mask=None):
    """The foreground on its navy ground; mask 'circle' or 'rounded' for legacy icons."""
    fg = open(os.path.join(HERE, "sumbee-foreground.svg")).read()
    inner = re.search(r"<svg[^>]*>(.*)</svg>", fg, re.S).group(1)
    clip = {
        None: "",
        "circle": '<clipPath id="m"><circle cx="54" cy="54" r="50"/></clipPath>',
        "rounded": '<clipPath id="m"><rect x="4" y="4" width="100" height="100" rx="22"/></clipPath>',
    }[mask]
    g = ' clip-path="url(#m)"' if mask else ""
    t = f"translate(54 54) scale({scale}) translate(-54 -54)"
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 108 108" width="{size}" height="{size}">'
            f"<defs>{clip}</defs><g{g}><rect width=\"108\" height=\"108\" fill=\"{NAVY}\"/>"
            f'<g transform="{t}">{inner}</g></g></svg>')


def feature_svg():
    """The 1024×500 Play feature graphic: the bee, the wordmark, the tagline and the four operation
    chips. Key content stays clear of the edges, which Play may crop or cover."""
    fg = open(os.path.join(HERE, "sumbee-foreground.svg")).read()
    bee = re.search(r"<svg[^>]*>(.*)</svg>", fg, re.S).group(1)
    chips = "".join(
        f'<g transform="translate({456 + i * 92} 340)"><rect width="76" height="76" rx="22" fill="{SUN}"/>'
        f'<text x="38" y="58" text-anchor="middle" font-family="Baloo 2" font-weight="800" font-size="60" '
        f'fill="{NAVY}">{op}</text></g>'
        for i, op in enumerate("+−×÷"))
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 500" width="1024" height="500">'
            f'<rect width="1024" height="500" fill="{NAVY}"/>'
            f'<g transform="translate(240 250) scale(5.6) translate(-54 -54)">{bee}</g>'
            f'<text x="448" y="214" font-family="Baloo 2" font-weight="800" font-size="128" fill="{SUN}">Sumbee</text>'
            f'<text x="456" y="284" font-family="Nunito" font-weight="700" font-size="38" fill="{WHITE}">'
            f"Daily math practice for kids</text>{chips}</svg>")


def render(svg, size, out, height=None):
    with tempfile.NamedTemporaryFile("w", suffix=".svg", delete=False) as f:
        f.write(svg)
    # Text uses the app's bundled fonts, so point fontconfig at res/font instead of system fonts.
    with tempfile.NamedTemporaryFile("w", suffix=".conf", delete=False) as conf:
        conf.write(f'<?xml version="1.0"?><fontconfig><dir>{os.path.join(RES, "font")}</dir>'
                   f"<cachedir>{tempfile.gettempdir()}/sumbee-fontconfig</cachedir></fontconfig>")
    env = dict(os.environ, FONTCONFIG_FILE=conf.name, PANGOCAIRO_BACKEND="fc")
    subprocess.run(["rsvg-convert", "-w", str(size), "-h", str(height or size), f.name, "-o", out],
                   check=True, env=env)
    os.unlink(f.name)
    os.unlink(conf.name)


def main():
    os.makedirs(os.path.join(RES, "drawable"), exist_ok=True)
    open(os.path.join(RES, "drawable", "ic_launcher_foreground.xml"), "w").write(FOREGROUND)
    open(os.path.join(RES, "drawable", "ic_launcher_monochrome.xml"), "w").write(MONOCHROME)

    # Legacy launchers (API 24–25) take a finished bitmap: the bee a little larger, since there's
    # no adaptive mask cropping the edges.
    for density, px in {"mdpi": 48, "hdpi": 72, "xhdpi": 96, "xxhdpi": 144, "xxxhdpi": 192}.items():
        d = os.path.join(RES, f"mipmap-{density}")
        os.makedirs(d, exist_ok=True)
        render(full_svg(px, 1.3, "rounded"), px, os.path.join(d, "ic_launcher.png"))
        render(full_svg(px, 1.3, "circle"), px, os.path.join(d, "ic_launcher_round.png"))

    open(os.path.join(HERE, "sumbee-full.svg"), "w").write(full_svg(108))
    render(full_svg(512, 1.3), 512, os.path.join(HERE, "play-store-512.png"))
    render(feature_svg(), 1024, os.path.join(HERE, "play-feature-1024x500.png"), height=500)


if __name__ == "__main__":
    main()
